language: go
go:
  - 1.4
  - 1.5
  - 1.6
  - tip

before_install:
- export OLD_BUILD_DIR=$TRAVIS_BUILD_DIR
- export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/zeropage/mukgoorm
- mv "$OLD_BUILD_DIR $TRAVIS_BUILD_DIR"

install:
# - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
# - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- echo "$TRAVIS_BUILD_DIR"
# - go get github.com/$(echo $PR | cut -d'/' -f 5-6)
- go get github.com/zeropage/mukgoorm

script: go test ./...
